export const DATE_FORMAT = 'YYYY-MM-DD'
export const DATE_ROUTE_FORMAT = 'YYYY/MM/DD'
export const CALENDAR_TAG_ID = 'monthCalendar'
export const DATE_REQEUST_FORMAT = 'YYYY-MM-DDTHH:mm:ss'
export const ACCESS_TOKEN = 'AccessToken'
